name: build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: target

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install cargo-llvm-cov and cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-make

      - name: Generate coverage
        run: cargo make coverage

      - name: Run cargo-fmt
        run: cargo-fmt

      - name: Run clippy
        run: cargo clippy -- --deny warnings

      - name: Build
        run: cargo build --release

      - name: Tests
        run: cargo test

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/selfoss-discord

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
